server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/css application/json text/plain application/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /downloads/ {
        alias /var/www/downloads/;
        autoindex off;
        default_type application/vnd.android.package-archive;
        add_header Content-Disposition 'attachment' always;
        add_header X-Content-Type-Options nosniff always;
    }
}
